"""add structured evidence fields

Revision ID: 5755b1ecac87
Revises: 9cb97a72640f
Create Date: 2026-08-19 09:08:10.465040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5755b1ecac87'
down_revision: Union[str, Sequence[str], None] = '9cb97a72640f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_records', sa.Column('vision_description', sa.Text(), nullable=True))
    op.add_column('evidence_records', sa.Column('structured_observations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_records', 'structured_observations')
    op.drop_column('evidence_records', 'vision_description')
    # ### end Alembic commands ###
