FROM python:3.12-slim

WORKDIR /app

COPY requirements-frontend.txt .

RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY dashboard ./dashboard

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]