from typing import Dict, List


def select_chunking_strategy(
    comparison: Dict,
    preferred_strategy: str = None
) -> str:
    """
    Select a chunking strategy based on comparison metrics.

    If a preferred strategy is provided and exists in the comparison,
    it is selected directly.

    Otherwise, the strategy with the smallest average chunk length
    is selected.
    """

    valid_strategies = {
        name: metrics
        for name, metrics in comparison.items()
        if metrics.get("chunk_count", 0) > 0
    }

    if not valid_strategies:
        raise ValueError("No valid chunking strategies available")

    if preferred_strategy:
        if preferred_strategy not in valid_strategies:
            raise ValueError(
                f"Unknown chunking strategy: {preferred_strategy}"
            )

        return preferred_strategy

    return min(
        valid_strategies,
        key=lambda name: valid_strategies[name]["average_length"]
    )


def select_chunks(
    chunks_by_strategy: Dict[str, List[Dict]],
    strategy: str
) -> List[Dict]:
    """
    Return chunks generated by the selected strategy.
    """

    if strategy not in chunks_by_strategy:
        raise ValueError(
            f"Unknown chunking strategy: {strategy}"
        )

    return chunks_by_strategy[strategy]